name: .NET MAUI CI/CD (NET 9.0)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 9.0.100-preview.1.23115.2 # Укажите актуальную версию .NET 9.0 (preview)

    - name: Restore dependencies
      run: dotnet restore MDMApp.sln

    - name: Build project
      run: dotnet build MDMApp.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test MDMApp.sln --no-build --verbosity normal
